### ISSUE TITLE
Linkuri la documente pe data.infoeducatie.ro

### ISSUE THREAD

**Issue by palcu** [infoeducatie/infoeducatie-ui#141]

**Comment by robertdxyz** [comment]
Trebuie adaugat in design si proceduri de aplicare a regulamentului

http://data.infoeducatie.ro/manual/regulament.pdf
http://data.infoeducatie.ro/manual/proceduri-de-aplicare-regulament.pdf

http://data.infoeducatie.ro/manual/multimedia.pdf
http://data.infoeducatie.ro/manual/roboti.pdf
http://data.infoeducatie.ro/manual/utilitar.pdf
http://data.infoeducatie.ro/manual/web.pdf
http://data.infoeducatie.ro/manual/educational.pdf

**Comment by palcu** [comment]
Linkurile le văd puse.
