### ISSUE TITLE
Verificare pentru fișierele încărcate

### ISSUE THREAD

**Issue by alexcoman** [infoeducatie/infoeducatie-ui#158]
Pentru moment fișierele încărcate nu par a fi verificate înainte / validate.
Ar trebui o validare după extensie, size, rezoluție etc.

Acum se încarcă:

```
-rw-r-----  1 alex alex 1.7G Jul  1 18:22 bcbio-nextgen-docker-image.gz
```

**Comment by robertdxyz** [comment]
https://github.com/infoeducatie/infoeducatie-api/issues/90
