### ISSUE TITLE
Validare la adresa sursei

### ISSUE THREAD

**Issue by vtemian** [infoeducatie/infoeducatie-ui#166]

**Comment by vtemian** [comment]
As folosi https://www.npmjs.com/package/is-git-url, dar pentru consistenta o sa fac cu html5 patterns

**Comment by palcu** [comment]
Închis de https://github.com/infoeducatie/infoeducatie-ui/commit/50782c1643e23a1b7708608a037be15b9cd1ec18. Continuare în https://github.com/infoeducatie/infoeducatie-ui/issues/222.
