### ISSUE TITLE
Ancora in pagina despre pt contact

### ISSUE THREAD

**Issue by vtemian** [infoeducatie/infoeducatie-ui#174]
Momentan sunt in acceasi pagina si sunt 2 lucruri diferite

**Comment by robertdxyz** [comment]
In footer ar trebui sa apara si despre si contact

**Comment by robertdxyz** [comment]
Pana la urma facem asa. Lasam pagina la fel cum e. Cand dai pe link-ul de contact sa te duca in pagina despre dar sa faca scroll (probabil cu ancora) pana la datele de contact.

**Comment by vtemian** [comment]
@robertdolca nu stiu cum sa fac asta.
@palcu se poate? Aparent nu prea merge bine cu react-router.

**Comment by robertdxyz** [comment]
Separam in 2 pagini

**Comment by palcu** [comment]
Mai e valabil issue-ul ăsta? Dacă da, nu înțeleg ce trebuie să fac. Ca să faci un link ai http://rackt.github.io/react-router/#Link.

**Comment by robertdxyz** [comment]
Outdated
