### ISSUE TITLE
Detalii despre seminarii

### ISSUE THREAD

**Issue by alexcoman** [infoeducatie/infoeducatie-ui#187]
Cred că ar fi util ca pentru seminarii să fie afișate următoarele informații în cazul în care sunt disponibile:
- când va avea loc prezentarea ?
- undeva va avea loc prezentarea ?
- eventual un link către slide-uri dacă este disponibil (dacă este complicat se poate adăuga în descriere)

Mulțumesc,
Alex

**Comment by robertdxyz** [comment]
Fara link la slide momentan

**Comment by robertdxyz** [comment]
Link-ul il punem pe forum. Restul detaliilor in program.
