### ISSUE TITLE
Router HistoryLocation it's bad

### ISSUE THREAD

**Issue by catalinmiron** [infoeducatie/infoeducatie-ui#19]
Sterge HistoryLocation pentru ca are un comportament dubios. Nu face by default redirect catre `/#/` si rutele sunt construite fata `/#/path`. Codul de mai jos construieste corect url-urile.

``` javascript
Router.run(routes, function (Handler) {
  React.render(<Handler/>, document.getElementById('app'));
});
```

**Comment by robertdxyz** [comment]
Este in regula si fara `#` deoarece orice ruta este prinsa de web server.
