### ISSUE TITLE
Campuri obligatorii fara steluta

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/infoeducatie-ui#197]
Dl. Onea zice ca sunt la inregistrare campuri obligatorii fara steluta. Sunt?

**Comment by alexcoman** [comment]
La înscrierea concurentului nu este nici un astfel de caz.

**Comment by alexcoman** [comment]
La înscrierea proiectului, la secțiunea web următorul câmp este marcat necorespunzător:

`Link către surse și documentație`

**Comment by palcu** [comment]
Fixed de https://github.com/infoeducatie/infoeducatie-ui/commit/99506b081d230462a384a06f482ac4d96ad7dcbb
