### ISSUE TITLE
Scoatem clases 5-8

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/infoeducatie-ui#198]
Din dropdownul de la inregistrare scoatem clasele 5-8 si lasam doar 9-12

**Comment by alexandrucoman** [comment]
Domnul Daniel Popa mi-a spus că a rugat un elev să se înregistreze și să omită toate câmpurile fără * și a funcționat perfect.

O să încerc imediat să adaug un proiect să confirm acest lucru.
