### ISSUE TITLE
Pagina "Despre" și "Contact"

### ISSUE THREAD

**Issue by alexcoman** [infoeducatie/infoeducatie-ui#202]
Conținutul de pe pagina `Despre` actuală ar putea fi împărțit în două pagini diferite.
Informațiile despre concurs ar putea rămâne pe pagina `Despre` și modalitatea de a contacta juriul sau organizatorii să fie pe pagina `Contact`.

Mulțumesc,
Alex

**Comment by robertdxyz** [comment]
Duplicat https://github.com/infoeducatie/infoeducatie-ui/issues/174
