### ISSUE TITLE
Speed up website loading

### ISSUE THREAD

**Issue by palcu** [infoeducatie/infoeducatie-ui#203]
https://twitter.com/busaco4web/status/618006261108486144
# Simple
- [x] activate GZIP (solved 66% of our problems)
- [x] remove duplicated CSS that appears in bundle (solved 20% of our problems) https://github.com/infoeducatie/infoeducatie-ui/pull/230
- [x] inline fonts and minify images https://github.com/infoeducatie/infoeducatie-ui/pull/234 https://github.com/infoeducatie/infoeducatie-ui/pull/233
- [x] check if any pictures on the front page have not been compressed
- [x] use React production bundle (~500KB)
- [x] ~~trim fonts (some 400KB of custom fonts there)~~ we still need them
- [x] do perf testing with Chrome audit
# Advanced
- [x] ~~webpack has automatically splitting of bundles. Remove the upload plugin and use it only on the register form~~ too difficult w/ React router... isomorphism w/ relay should solve this
- [x] Cloudflare https://github.com/infoeducatie/infoeducatie-ui/issues/229

**Comment by palcu** [comment]
- [x] ~~foloseste chestia asta https://github.com/tcoopman/image-webpack-loader pentru optimizarea imaginilor on the spot in productie~~ am facut de mana

**Comment by palcu** [comment]
Las asta aici ca poate am nevoie: https://github.com/reddit/reddit-mobile/issues/247

**Comment by robertdxyz** [comment]
Este de ajuns momentan. Mai revizitam asta in viitor.
