### ISSUE TITLE
Validare URL pentru Github

### ISSUE THREAD

**Issue by alexcoman** [infoeducatie/infoeducatie-ui#222]
Ar trebui să acceptăm și URL-urile care nu se termină în `.git`. E posibil ca mulți participanți să copie adresa URL direct din browser.

Pentru a rezolva problema trebuie schimbată expresia din:

```
((git|ssh|http(s)?)|(git@[\w\.]+))(:(//)?)([\w\.@\:/\-~]+)(\.git)(/)?
```

în

```
((git|ssh|http(s)?)|(git@[\w\.]+))(:(//)?)([\w\.@\:/\-~]+)(\.git)?(/)?
```

**Comment by robertdxyz** [comment]
Cred ca cel mai bine cerem URL-ul din browser de la toti. Adica le spunem sa ne dea adresa din browser in textul de sub camp.

In felul asta daca il afisam pe forum va fi super usor de vazut codul dand click.

**Comment by robertdxyz** [comment]
Si in felul asta e si usor de gasit URL-ul.

**Comment by alexcoman** [comment]
Putem folosi expresia de mai sus, și la afișare putem șterge `.git` dacă există.

**Comment by robertdxyz** [comment]
Eu as scoate git@ ca nu se poate da click direct pe URL

**Comment by alexcoman** [comment]
Păi nu mi se pare ok să respingi un URL valid.
Dacă ne încurcă `.git` putem să îl eliminăm când îl afișăm / trimitem spre API.

**Comment by robertdxyz** [comment]
Eu nu viceam de .git la sfarsit cu git@ adica SSH

**Comment by alexcoman** [comment]
În cazul acesta putem folosi:

```
https://gitbub.com([\w\.@\:/\-~]+)(\.git)?(/)?
```

Sau mai restrictiv:

```
https://github.com/[^/]+/[^/]+(\.git)?(/)?
```
