### ISSUE TITLE
Proiectele din anii anteriori

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/infoeducatie-ui#244]
- [x] Se trage din API lista de editii si se afiseaza intr-un dropdown sau intr-o lista https://github.com/infoeducatie/infoeducatie-api/pull/122
- [x] Cand se schimba editia
  - [x] Se schimba editia in header
  - [x] Se actualizeaza lista de proiecte (in anii trecuti s-ar putea sa nu fie toate categoriile)
  - [x] Se actualizeaza URL-ul

**Comment by vtemian** [comment]
Mai trebuie in API sa filtreze dupa editie:
https://github.com/infoeducatie/infoeducatie-api/blob/master/app/controllers/v1/projects_controller.rb#L11

**Comment by robertdxyz** [comment]
Mai trebuie actualizat nr de judete, participanti si proiecte
