### ISSUE TITLE
Resurse încărcate de pe HTTP

### ISSUE THREAD

**Issue by alexcoman** [infoeducatie/infoeducatie-ui#286]
Pentru moment gravatarul este încarcat folosind HTTP.
Acest lucru ar trebui schimbat.

Mulțumesc,
Alex

**Comment by robertdxyz** [comment]
Ar trebui folosita functia getGravatarImage in ambele locuri

**Comment by vtemian** [comment]
Tot aia face. Dar da, putem sa o folosim

On Thu, Jul 16, 2015 at 9:17 PM, Robert Dolca notifications@github.com
wrote:

> Ar trebui folosita functia getGravatarImage in ambele locuri
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/infoeducatie/infoeducatie-ui/issues/286#issuecomment-122039615
> .

## 

Vlad

**Comment by robertdxyz** [comment]
Ideea era sa nu avem cod duplicat nu ca e ceva diferit
