### ISSUE TITLE
Corectari text engleza

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/infoeducatie-ui#292]

**Comment by popadaniel72** [comment]
De schimbat textul in engleza de la alumnus a.i. sa fie acelasi text ca in romana. NU cel in care apare cuvantul infoarena!

**Comment by alexcoman** [comment]
A corectat @vtemian în https://github.com/infoeducatie/infoeducatie-ui/commit/c6598832c4e99108e764c9a1450b9c6437fd429a.

**Comment by robertdxyz** [comment]
[eng.docx](https://github.com/infoeducatie/infoeducatie-ui/files/763/eng.docx)
