### ISSUE TITLE
Logo Girls Who Code

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/infoeducatie-ui#293]
![gwc_v2](https://cloud.githubusercontent.com/assets/383543/8738669/63ee7e72-2c3b-11e5-8207-c75c77a1b647.png)

**Comment by vtemian** [comment]
Ce categorie de sponsori?

**Comment by robertdxyz** [comment]
bronze

**Comment by vtemian** [comment]
O sa pun pagina de facebook ca link fiindca site-ul e in constructie

**Comment by alexcoman** [comment]
E ok.
