### ISSUE TITLE
Scoatem de la proiecte view-ul cu box-uri

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/infoeducatie-ui#303]
Pe desktop nu este implicit si este  greu de urmarit. Pe mobil e dezactivat.
Nu are rost sa il mai intretinem.

**Comment by hurrycane** [comment]
Discutat cu Robert pe privat. Mai bine mai incercam sa facem tabelul de participanti mai bun decat sa pierdem timpul sa scoatem cod.
