### ISSUE TITLE
Link text care sa duca la forum pentru seminarii

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/infoeducatie-ui#306]
Ceva exprima-ti parerea / comenteaza

**Comment by vtemian** [comment]
Scoatem link-ul de pe card si il lasam doar pe `Comenteaza`?

**Comment by robertdxyz** [comment]
Cred ca da. Nu?

**Comment by robertdxyz** [comment]
si nu spune comenteaza, eu as merge pe `discuta` sau `spune-te parerea`
