### ISSUE TITLE
Program pe site

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/infoeducatie-ui#313]
https://docs.google.com/spreadsheets/d/1xUGzj0ar_6bluOhuz6poSG-34buiuMXi_PJb9LjDFuc/pubhtml#

**Comment by vtemian** [comment]
Ar fi interesant sa punem si link-uri la talk-uri pe forum, direct in program și să diferențiem un pic programul pe categorii: talk-urile le coloram într-un fel, cina, deschiderea, focul de tabara, premierea in alt fel etc.
