### ISSUE TITLE
Afiseaza judetele de la toti participantii de la proiect daca sunt diferite

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/infoeducatie-ui#316]

**Comment by vtemian** [comment]
Din api ar trebui sa vina o lista de judete / participant

**Comment by robertdxyz** [comment]
https://github.com/infoeducatie/infoeducatie-api/issues/161

**Comment by robertdxyz** [comment]
Poti sa faci asta te rog sa pot face si eu deploy la API?

**Comment by vtemian** [comment]
Bah incerc....nah...fac tot ce pot...

**Comment by robertdxyz** [comment]
:))
