### ISSUE TITLE
All the routes should be in Romanian

### ISSUE THREAD

**Issue by vtemian** [infoeducatie/infoeducatie-ui#36]
Right now, we have English based routes like: `/jury`, `/sponsors`, `/contestants`.
In order to improve SEO and to be more consistent, because it's a Romanian website, we should have those routes in Romanian.

**Comment by palcu** [comment]
Bă da nu vorbisem să scriem în română aici-șa?

**Comment by hurrycane** [comment]
E funny sa discutam sa punem rutele in romana dar discutia e in engleza.

**Comment by vtemian** [comment]
Română să fie!

On Sat, Jun 20, 2015 at 1:57 AM, Bogdan Gaza notifications@github.com
wrote:

> E funny sa discutam sa punem rutele in romana dar discutia e in engleza.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/infoeducatie/infoeducatie-ui/issues/36#issuecomment-113665218
> .

## 

Vlad
