### ISSUE TITLE
Rezultate din anii trecuti

### ISSUE THREAD

**Issue by palcu** [infoeducatie/infoeducatie-ui#43]
Doar embed

**Comment by vtemian** [comment]
As zice sa nu implementam nimic si in tabara sa facem rezultatele pe bune.

On Sat, Jun 20, 2015 at 12:27 PM, Alex Palcuie notifications@github.com
wrote:

> Doar embed
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/infoeducatie/infoeducatie-ui/issues/43.

## 

Vlad

**Comment by palcu** [comment]
Nu, că vrem să îi arătăm lui Onea că măcar e funcțional, chiar dacă nu e frumos

**Comment by vtemian** [comment]
Tot improvizatie?

2015-06-20 14:59 GMT+03:00 Alex Palcuie notifications@github.com:

> Nu, că vrem să îi arătăm lui Onea că măcar e funcțional, chiar dacă nu e
> frumos
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/infoeducatie/infoeducatie-ui/issues/43#issuecomment-113751057
> .

## 

Vlad

**Comment by palcu** [comment]
Dă-i înainte cu tupeu...

**Comment by hurrycane** [comment]
E cu prioritate redusa asta. Trebuie macar anul trecut.
