### ISSUE TITLE
Imagini pentru paginile statice

### ISSUE THREAD

**Issue by vtemian** [infoeducatie/infoeducatie-ui#59]
- [x] imaginea din header pentru contact
- [x] imaginea din header pentru poze
- [x] imaginea din header pentru alumni
- [x] imaginea din header pentru rezultate
- [ ] pozele cu fețele alumniilor

**Comment by robertdxyz** [comment]
![vivi](https://cloud.githubusercontent.com/assets/383543/8342441/c1f5de3e-1ad4-11e5-9937-a707a3111b51.png)
![cristi](https://cloud.githubusercontent.com/assets/383543/8342442/c1fad8c6-1ad4-11e5-87a7-2b539e3c4187.png)
![header-about](https://cloud.githubusercontent.com/assets/383543/8342443/c1fc4ee0-1ad4-11e5-9649-e503ddd017f0.png)
![header-alumni](https://cloud.githubusercontent.com/assets/383543/8342444/c2016254-1ad4-11e5-9d9e-eaf485678e19.png)
![header-photos](https://cloud.githubusercontent.com/assets/383543/8342445/c2026488-1ad4-11e5-9f09-041a1c2c902e.png)
![tudor](https://cloud.githubusercontent.com/assets/383543/8342446/c205ecde-1ad4-11e5-87d2-70e94d5724ff.png)

@vtemian ok?

**Comment by vtemian** [comment]
@robertdolca alumni poti sa ii lasi cu background transparent?

**Comment by palcu** [comment]
Mai e de actualitate?
