### ISSUE TITLE
Admin panel generale

### ISSUE THREAD

**Issue by palcu** [infoeducatie/infoeducatie-ui#95]
- [ ] Vom avea in components un folder `admin`
- [ ]  Va fi o rută mare de admin cu rute nested de:
- index - aici vei avea:
  - statistici despre cate stiri are editia curenta
  - statisticii despre cati participanti sunt
  - posibilitatea de a face o editie noua 
  - de a selecta ca si current edition o editie veche din lista de editii
- știri
- particpanți
- [ ] Pe /current userul va avea un flag dacă este admin
- [ ] În header ul normal, dacă userul este admin o sa-i apara butonul de admin
- [ ] Va exista un header separat de admin cu toate linkurile de rute

**Comment by robertdxyz** [comment]
Pentru admin cred ca trebuie si header si footer diferit. La fel si un meniu de bootstrap clasic. In rest LGTM
